services:
  - docker

sudo: false
language: c

env:
  - tag=latest
  - tag=pg11-geos37-gdal23-proj52
  - tag=pg10-geos36-gdal23-proj49
  - tag=pg96-geos36-gdal22-proj49
  - tag=pg95-geos36-gdal22-proj49
  - tag=pg94-geos35-gdal111-proj48

matrix:
  allow_failures:
    - env: tag=latest

script:
  - echo "FROM postgis/postgis-build-env:${tag}" > Dockerfile
  - echo "ADD --chown=postgres:postgres . /src/postgis" >> Dockerfile
  - echo "CMD ci/travis/run_tests.sh" >> Dockerfile
  - docker build -t pgtest .
  - docker run --name pgtest-${TRAVIS_BUILD_NUMBER} pgtest

after_success:
  - docker cp pgtest-${TRAVIS_BUILD_NUMBER}:/src/liblwgeom .
  - docker cp pgtest-${TRAVIS_BUILD_NUMBER}:/src/postgis .
  - docker cp pgtest-${TRAVIS_BUILD_NUMBER}:/src/loader .
  - docker rm pgtest-${TRAVIS_BUILD_NUMBER}
  - bash .github/codecov.bash

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#postgis-activity"
    on_success: change
    on_failure: always
    use_notice: false
