# ------------------------------------------------------------------------------
# appVeyor script
# Copyright(c) pgRouting Contributors
#
# Main configuration
# ------------------------------------------------------------------------------

version: 3.0.{build}

image: Visual Studio 2013
configuration: Release
platform: x64

clone_depth: 1
clone_folder: c:\build\postgis

services:
  - postgresql101

environment:
  CONFIGURATION: Release
  BUILD_ROOT_DIR: c:\build
  CYG_ROOT: C:/MinGW/msys/1.0
  PG_VER: 10.1

install:
  - ps: |
        $env:PATH="$env:CYG_ROOT\bin;C:\MinGW\bin;$($env:PATH)"
        mingw-get install autotools autoconf automake
        bash -lc "echo 'C:\MinGW   /mingw' > /etc/fstab"

build_script:
  - ps: |
        $env:APPVEYOR_BUILD_FOLDER = $env:APPVEYOR_BUILD_FOLDER -replace "\\", "/"
        bash -lc "cd $env:APPVEYOR_BUILD_FOLDER; ./autogen.sh && ./configure && make"

test_script:
  - set PGUSER=postgres
  - set PGPASSWORD=Password12!
  - set PGHOME=C:\Progra~1\PostgreSQL\%PG_VER%
  - set PGPORT=5432
  - set PATH=%PATH%;%PGHOME%\bin
